name: Github Action Workflow DEV

on:
  push:
    branches:
      - develop
  repository_dispatch:
    types:
      - build-dev
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dev:
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      CI_ENV: dev
    secrets:
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: ${{secrets.AWS_DEFAULT_REGION}}
